config/routes.rb
Rails.application.routes.draw do
  resources :actor_anthologies
  resources :point_of_interests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "point_of_interests#index"
end

app/models/actor_anthology.rb
class ActorAnthology < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/point_of_interest.rb
class PointOfInterest < ApplicationRecord
  before_save :build_lat_long_from_coords
  
  def build_lat_long_from_coords
    if self.coords && (self.latitude.nil? || self.longitude.nil?)
      lat = coords.split(",").first.to_f
      long = coords.split(",").last.to_f
      self.latitude = lat
      self.longitude = long
    end
  end
end

app/controllers/actor_anthologies_controller.rb
class ActorAnthologiesController < ApplicationController
  before_action :set_actor_anthology, only: %i[ show edit update destroy ]

  # GET /actor_anthologies or /actor_anthologies.json
  def index
    @actor_anthologies = ActorAnthology.all
  end

  # GET /actor_anthologies/1 or /actor_anthologies/1.json
  def show
  end

  # GET /actor_anthologies/new
  def new
    @actor_anthology = ActorAnthology.new
  end

  # GET /actor_anthologies/1/edit
  def edit
  end

  # POST /actor_anthologies or /actor_anthologies.json
  def create
    @actor_anthology = ActorAnthology.new(actor_anthology_params)

    respond_to do |format|
      if @actor_anthology.save
        format.html { redirect_to actor_anthology_url(@actor_anthology), notice: "Actor anthology was successfully created." }
        format.json { render :show, status: :created, location: @actor_anthology }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor_anthology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actor_anthologies/1 or /actor_anthologies/1.json
  def update
    respond_to do |format|
      if @actor_anthology.update(actor_anthology_params)
        format.html { redirect_to actor_anthology_url(@actor_anthology), notice: "Actor anthology was successfully updated." }
        format.json { render :show, status: :ok, location: @actor_anthology }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor_anthology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actor_anthologies/1 or /actor_anthologies/1.json
  def destroy
    @actor_anthology.destroy

    respond_to do |format|
      format.html { redirect_to actor_anthologies_url, notice: "Actor anthology was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor_anthology
      @actor_anthology = ActorAnthology.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_anthology_params
      params.require(:actor_anthology).permit(:name, :picture_url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController
  before_action :set_point_of_interest, only: %i[ show edit update destroy ]

  # GET /point_of_interests or /point_of_interests.json
  def index
    @point_of_interests = PointOfInterest.all
  end

  # GET /point_of_interests/1 or /point_of_interests/1.json
  def show
  end

  # GET /point_of_interests/new
  def new
    @point_of_interest = PointOfInterest.new
  end

  # GET /point_of_interests/1/edit
  def edit
  end

  # POST /point_of_interests or /point_of_interests.json
  def create
    @point_of_interest = PointOfInterest.new(point_of_interest_params)

    respond_to do |format|
      if @point_of_interest.save
        format.html { redirect_to point_of_interest_url(@point_of_interest), notice: "Point of interest was successfully created." }
        format.json { render :show, status: :created, location: @point_of_interest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @point_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_of_interests/1 or /point_of_interests/1.json
  def update
    respond_to do |format|
      if @point_of_interest.update(point_of_interest_params)
        format.html { redirect_to point_of_interest_url(@point_of_interest), notice: "Point of interest was successfully updated." }
        format.json { render :show, status: :ok, location: @point_of_interest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @point_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_of_interests/1 or /point_of_interests/1.json
  def destroy
    @point_of_interest.destroy

    respond_to do |format|
      format.html { redirect_to point_of_interests_url, notice: "Point of interest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_of_interest
      @point_of_interest = PointOfInterest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def point_of_interest_params
      params.require(:point_of_interest).permit(:name, :latitude, :longitude, :description)
    end
end

app/helpers/actor_anthologies_helper.rb
module ActorAnthologiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_of_interests_helper.rb
module PointOfInterestsHelper
end

app/views/actor_anthologies/_actor_anthology.html.erb
<div id="<%= dom_id actor_anthology %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= actor_anthology.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Picture url:</strong>
    <%= actor_anthology.picture_url %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this actor anthology", actor_anthology, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this actor anthology', edit_actor_anthology_path(actor_anthology), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/actor_anthologies/_form.html.erb
<%= form_with(model: actor_anthology, class: "contents") do |form| %>
  <% if actor_anthology.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(actor_anthology.errors.count, "error") %> prohibited this actor_anthology from being saved:</h2>

      <ul>
        <% actor_anthology.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/actor_anthologies/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing actor anthology</h1>

  <%= render "form", actor_anthology: @actor_anthology %>

  <%= link_to "Show this actor anthology", @actor_anthology, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to actor anthologies", actor_anthologies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/actor_anthologies/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Actor anthologies</h1>
    <%= link_to 'New actor anthology', new_actor_anthology_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="actor_anthologies" class="min-w-full">
    <%= render @actor_anthologies %>
  </div>
</div>

app/views/actor_anthologies/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New actor anthology</h1>

  <%= render "form", actor_anthology: @actor_anthology %>

  <%= link_to 'Back to actor anthologies', actor_anthologies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/actor_anthologies/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @actor_anthology %>

    <%= link_to 'Edit this actor_anthology', edit_actor_anthology_path(@actor_anthology), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this actor_anthology', actor_anthology_path(@actor_anthology), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to actor_anthologies', actor_anthologies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-200 -mb-10">
  <div class="max-w-5xl mx-auto">
    <div class="flex justify-between px-8">
      <div class="flex space-x-4">
            
        <div class="flex space-x-4">
          <a href="/" class="flex items-center py-5 px- text-gray-700">
            <svg class="h6 w-6 mr-2 text-blue-500 py-3" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
            <span class="font-bold">Leaflet.js Practice</span>
          </a>
        </div>
        
        <div class="flex items-center space-x-3">
          <%= link_to "About", "https://github.com/josh-works/polyline-practice/tree/main#about-this-project", class: "py-5 px-1 text-gray-700 hover:text-gray-900" %>
          <%= link_to "Sponsor This Project", "https://github.com/sponsors/josh-works", class: "py-5 px-1 text-gray-700 hover:text-gray-900" %>
        </div>
      </div>
    
    <div class="flex items-center space-x-1">
      <a href="#" class="py-5 px-3">Login</a>
      <a href="#" class="py-2 px-3 bg-yellow-400 hover:bg-yellow-300 text-yell0w-800 hover:text-yellow-900 rounded transition duration-300">Signup</a>
    </div>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolylinePractice</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/point_of_interests/_form.html.erb
<%= form_with(model: point_of_interest, class: "contents") do |form| %>
  <% if point_of_interest.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(point_of_interest.errors.count, "error") %> prohibited this point_of_interest from being saved:</h2>

      <ul>
        <% point_of_interest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="h-80 px-5">
    <div id="map" class="h-80 flex"></div>
  </div>

<script type="text/javascript">
  latitude = 39.766444
  longitude = -105.228456
  console.log(latitude, longitude);
  var map = L.map('map').setView([latitude, longitude], 18);
  L.tileLayer(
    'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 22,
    }).addTo(map);

   
   // diagnostic/placement helpers
var popup = L.popup();
function onMapClick(e) {
  popup
      .setLatLng(e.latlng)
      .setContent("You clicked the map at " + e.latlng.toString())
      .openOn(map);
  console.log("You clicked the map at " + e.latlng);
}

map.on('click', onMapClick);
</script>

  <div class="my-5">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/point_of_interests/_map_all_points.html.erb
<div id="<%= dom_id point_of_interest %>" class="flex-col">
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= point_of_interest.description %>
  </p>
  
  <!-- leaflet map, make partial later -->
  <div class="h-80 px-5">
    <div id="map" class="h-40 flex"></div>
    <div id="map-sat-view" class="h-40 flex"></div>
  </div>

<script type="text/javascript">
  latitude = "<%= point_of_interest.latitude %>"
  longitude = "<%= point_of_interest.longitude %>"
  description = "<%= point_of_interest.description %>"
  console.log(latitude, longitude);
  var map = L.map('map').setView([latitude, longitude], 19);
  L.tileLayer(
    'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 22,
    }).addTo(map);

  var mymap = L.map('map-sat-view').setView([latitude, longitude], 19);
  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 22,
    id: 'mapbox/satellite-v9',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: 'pk.eyJ1Ijoiam9zaHdvcmtzIiwiYSI6ImNrcWk2NzUxeTJhbm8yem4weDFreTY5bjQifQ.Qja1F9B1-i7hK3KOvSYAvg'
  }).addTo(mymap);
      
  var MobilityIcon = L.Icon.extend({
    options: {
      shadowUrl: '',
      iconSize:     [60, 60],
      shadowSize:   [10,10],
      }
    });
  // var wheelchairConfused = new MobilityIcon({iconUrl: 'wheelchair-confused-red.png'});
  // var bikerWalkerAccident = new MobilityIcon({iconUrl: 'biker-walker-accident-red.png'});
  // var driverWalkerAccident = new MobilityIcon({iconUrl: 'driver-walker-accident-red.png'});
  // var walkerAccident = new MobilityIcon({iconUrl: 'walker-accident-red.png'});
  // var driverBikerAccident = new MobilityIcon({iconUrl: "<%= image_url('biker-walker-rrraccident-red.png') %>"  });
 
  // // car-bike conflict areas
  // L.marker([latitude, longitude], {icon: driverBikerAccident}).addTo(map)
  //  .bindPopup(description);
  // 
  // L.marker([latitude, longitude], {icon: driverBikerAccident}).addTo(mymap)
  //  .bindPopup(description);
   
   // diagnostic/placement helpers
var popup = L.popup();
function onMapClick(e) {
  popup
      .setLatLng(e.latlng)
      .setContent("You clicked the map at " + e.latlng.toString())
      .openOn(map);
  console.log("You clicked the map at " + e.latlng);
}

map.on('click', onMapClick);
mymap.on('click', onMapClick);
</script>


  <p class="my-5">
    <strong class="block font-medium mb-1">Lat/Long:</strong>
    <%= point_of_interest.longitude %>, <%= point_of_interest.latitude %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this point of interest", point_of_interest, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this point of interest', edit_point_of_interest_path(point_of_interest), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/point_of_interests/_mapbox_map.html.erb
<!-- leaflet map, make partial later -->


  <script type="text/javascript">
    regMapDiv = "<%= 'map-' + @point_of_interest.id.to_s %>"
    satMapDiv = "<%= 'map-sat-view' + @point_of_interest.id.to_s %>"
    latitude = "<%= @point_of_interest.latitude %>"
    longitude = "<%= @point_of_interest.longitude %>"
    description = "<%= @point_of_interest.description %>"
    
    // var wheelchairConfused = new MobilityIcon({iconUrl: 'wheelchair-confused-red.png'});
    // var bikerWalkerAccident = new MobilityIcon({iconUrl: 'biker-walker-accident-red.png'});
    // var driverWalkerAccident = new MobilityIcon({iconUrl: 'driver-walker-accident-red.png'});
    // var walkerAccident = new MobilityIcon({iconUrl: 'walker-accident-red.png'});
    // var driverPed = new MobilityIcon({iconUrl: "<%= image_url('crossroad.png') %>"  });
    // var roundabout = new MobilityIcon({iconUrl: "<%= image_url('crossroad.png') %>"  });
    // 
    console.log(latitude, longitude);
    var map = L.map(regMapDiv).setView([latitude, longitude], 19);
    L.tileLayer(
      'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          maxZoom: 22,
      }).addTo(map);

    var mymap = L.map(satMapDiv).setView([latitude, longitude], 19);
    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 22,
      id: 'mapbox/satellite-v9',
      tileSize: 512,
      zoomOffset: -1,
      accessToken: 'pk.eyJ1Ijoiam9zaHdvcmtzIiwiYSI6ImNrcWk2NzUxeTJhbm8yem4weDFreTY5bjQifQ.Qja1F9B1-i7hK3KOvSYAvg'
    }).addTo(mymap);
        
    var MobilityIcon = L.Icon.extend({
      options: {
        shadowUrl: '',
        iconSize:     [60, 60],
        shadowSize:   [10,10],
        }
      });

    // L.marker([latitude, longitude], {icon: driverPed}).addTo(map)
    //  .bindPopup(description);
    // 
    // L.marker([latitude, longitude], {icon: roundabout}).addTo(mymap)
    //  .bindPopup(description);
     
     // diagnostic/placement helpers
    var popup = L.popup();
    function onMapClick(e) {
      popup
          .setLatLng(e.latlng)
          .setContent("You clicked the map at " + e.latlng.toString())
          .openOn(map);
      console.log("You clicked the map at " + e.latlng);
    }

    map.on('click', onMapClick);
    mymap.on('click', onMapClick);
  </script>
<!-- leaflet map, make partial later -->

app/views/point_of_interests/_point_of_interest.html.erb
<div id="<%= dom_id point_of_interest %>" class="flex-col">
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= point_of_interest.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Lat/Long:</strong>
    <%= point_of_interest.longitude %>, <%= point_of_interest.latitude %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this point of interest", point_of_interest, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this point of interest', edit_point_of_interest_path(point_of_interest), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/point_of_interests/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing point of interest</h1>

  <%= render "form", point_of_interest: @point_of_interest %>

  <%= link_to "Show this point of interest", @point_of_interest, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to point of interests", point_of_interests_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/point_of_interests/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Points of Interest</h1>
    <%= link_to 'New point of interest', new_point_of_interest_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  
  <div class="h-80 px-5">
    <div id="map" class="h-80 flex"></div>
  </div>
  
  <script type="text/javascript">
    regMapDiv = "map"
    
    const pointsOfInterest = () => {
      let url = 'http://localhost:3000/point_of_interests.json'
      fetch(url)
       .then((response) => { return response.json(); })
       .then(response => obj = data);
    }

function printToConsole(data) {
  data.map(console.log(x);)
}
    
    var obj;

fetch('https://jsonplaceholder.typicode.com/posts/1')
  .then(res => res.json())
  .then(data => obj = data)
  .then(() => console.log(obj))
console.log(obj);
    
    var map = L.map(regMapDiv).setView([39.76622709413315,-105.22932827525855], 19);
    L.tileLayer(
      'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          maxZoom: 22,
      }).addTo(map);

    
        
    var MobilityIcon = L.Icon.extend({
      options: {
        shadowUrl: '',
        iconSize:     [60, 60],
        shadowSize:   [10,10],
        }
      });
    // var wheelchairConfused = new MobilityIcon({iconUrl: 'wheelchair-confused-red.png'});
    // var bikerWalkerAccident = new MobilityIcon({iconUrl: 'biker-walker-accident-red.png'});
    // var driverWalkerAccident = new MobilityIcon({iconUrl: 'driver-walker-accident-red.png'});
    // var walkerAccident = new MobilityIcon({iconUrl: 'walker-accident-red.png'});
    var driverBikerAccident = new MobilityIcon({iconUrl: "<%= image_url('biker-walker-accident-red.png') %>"  });
    var crossroad = new MobilityIcon({iconUrl: "<%= image_url('crossroad.png') %>"  });
    
    // car-bike conflict areas
  
     // diagnostic/placement helpers
    var popup = L.popup();
    function onMapClick(e) {
      popup
          .setLatLng(e.latlng)
          .setContent("You clicked the map at " + e.latlng.toString())
          .openOn(map);
      console.log("You clicked the map at " + e.latlng);
    }

    map.on('click', onMapClick);
  
  </script>

  <div id="point_of_interests" class="min-w-full">
    <%= render @point_of_interests %>
  </div>
</div>

app/views/point_of_interests/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New point of interest</h1>

  <%= render "form", point_of_interest: @point_of_interest %>

  <%= link_to 'Back to point of interests', point_of_interests_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/point_of_interests/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @point_of_interest %>

    <%= link_to 'Edit this point_of_interest', edit_point_of_interest_path(@point_of_interest), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this point_of_interest', point_of_interest_path(@point_of_interest), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to point_of_interests', point_of_interests_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>